# Generated by Django 4.2.11 on 2024-04-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participates_in',
            options={'verbose_name_plural': 'Participates In'},
        ),
    ]
